### ISSUE TITLE
Uncaught TypeError: Cannot set property 'evidence' of undefined

### ISSUE THREAD

**Issue by liphvf** [induane/simple-flake8#1]
[Enter steps to reproduce below:]
1. Use simple-flake8 troggle.

**Atom Version**: 1.0.2
**System**: Debian GNU/Linux
**Thrown From**: [simple-flake8](https://github.com/induane/simple-flake8) package, v0.9.7
### Stack Trace

Uncaught TypeError: Cannot set property 'evidence' of undefined

```
At /home/liphvf/.atom/packages/simple-flake8/lib/simple-flake8-view.coffee:45

TypeError: Cannot set property 'evidence' of undefined
    at LineStream.<anonymous> (/home/liphvf/.atom/packages/simple-flake8/lib/simple-flake8-view.coffee:50:43)
    at emitOne (events.js:77:13)
    at LineStream.emit (events.js:166:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at LineStream.Readable.push (_stream_readable.js:109:10)
    at LineStream.Transform.push (_stream_transform.js:128:32)
    at LineStream._transform (/home/liphvf/.atom/packages/simple-flake8/node_modules/byline/lib/byline.js:110:17)
    at LineStream.Transform._read (_stream_transform.js:167:10)
    at LineStream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:295:12)
```
### Commands

```
     -0:07.3.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  5x -0:04.5.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:01.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:00.9.0 simple-flake8:toggle (atom-text-editor.editor)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "markdown-format",
      "you-complete-me",
      "markdown-preview-plus",
      "linter-flake8"
    ],
    "themes": [
      "one-dark-ui",
      "monokai"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
autoclose-html, v0.18.0
autocomplete-plus-python-jedi, v0.3.6
color-picker, v2.0.9
git-diff-details, v0.18.0
highlight-selected, v0.10.1
linter, v1.2.4
markdown-scroll-sync, v0.4.0
markdown-table-formatter, v2.5.2
minimap, v4.12.0
monokai, v0.14.0
seti-icons, v0.3.1
simple-flake8, v0.9.7

# Dev
No dev packages
```

This error appear for me. Thanks for your work, and please. fix it.

**Comment by induane** [comment]
Interesting, and sorry it took me so long to respond. I'll check into it and see what I can find!

**Comment by induane** [comment]
I put in a potential fix that might fix the crash you're experiencing. I was unable to reproduce it locally though so if you try the latest version without success please let me know if it continues to fail for you. Thanks!

**Comment by liphvf** [comment]
That error fix, but... when i use simple-flake8 toggle command. , my printer  dialog appear for me. Show this video. For better quality download it. [https://www.dropbox.com/s/i02jyxyxec5szz2/simple-flake8-printer-error.mp4?dl=0](https://www.dropbox.com/s/i02jyxyxec5szz2/simple-flake8-printer-error.mp4?dl=0) Thanks for your attention.

**Comment by induane** [comment]
Hah that's a pretty weird one. Thanks for the video, I didn't notice it at first so sorry about that.

Try 0.9.9 which I just pushed. I believe it fixes the print dialog issue.

**Comment by liphvf** [comment]
Fix all. Thanks for your attention and your time.
