### ISSUE TITLE
Request - allow Flake8 Plugins

### ISSUE THREAD

**Issue by mer60** [induane/simple-flake8#3]
Hi, here is another user of your really nice package ...

In your simple-flake8-view.coffee you have the following lines:

Basic flake8 parsing tool with callback functionality
flake = (filePath, callback) ->
  line_expr = /:(\d+):(\d+): ([**CEFW**]\d{3}) (.*)/

The line_expr is OK when you only use standard-flake8 without plugins

I've changed the line expression like this

  line_expr = /:(\d+):(\d+): ([**_A-Z_**]\d{3}) (.*)/

so I'm able to use any flake8-plugin I like

Maybe you want to implement this ...

**Comment by induane** [comment]
Very cool - I'll take a look at testing that out. Thanks for the suggestion!

**Comment by induane** [comment]
Added in decaffinated release 0.10.0  - thanks for the suggestion!
